[feat][WIP] add a method option to disable check eovercrowded on server side
apache/brpc pull request #2774
Opened 2024-09-30 06:37 UTC by superhail

### What problem does this PR solve?

Issue Number:

Problem Summary: Sometimes we need to disable check eovercrowded for some methods

### What is changed and the side effects?

Changed: add a method/service level option to disable check eovercrowded on server side

Side effects:
- Performance effects(性能影响): zero/or little

- Breaking backward compatibility(向后兼容性): no breaking

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](https://github.com/apache/brpc/blob/master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

2024-09-30 16:27 UTC, chenBright requested changes

2024-09-30 16:27 UTC, chenBright commented on src/brpc/server.h
> +    bool& IgnoreEovercrowdedOf(const butil::StringPiece& full_method_name);
ignore_eovercrowded是Socket（连接级别）的属性，只需要支持server级别ignore_eovercrowded即可，不需要支持method级别的。因为当连接eovercrowded后，支持ignore_eovercrowded的方法一直能写，不支持ignore_eovercrowded的方法一直写不了，这是不公平的。

2024-09-30 16:27 UTC, chenBright commented on src/brpc/server.h
> +        bool ignore_eovercrowded = false;
统一在构造函数初始化？

2024-10-07 06:51 UTC, wwbmmm commented
What is the usage scenario of this feature?

2024-10-07 08:26 UTC, superhail commented on src/brpc/server.h
> +    bool ignore_eovercrowded;
ok

2024-10-07 08:26 UTC, superhail commented on src/brpc/server.h
> +        bool ignore_eovercrowded = false;
ok

2024-10-07 08:27 UTC, superhail commented on src/brpc/server.h
> +    bool& IgnoreEovercrowdedOf(const butil::StringPiece& full_method_name);
ok

2024-10-07 08:33 UTC, superhail commented
@wwbmmm we have some control-frame methods which we hope will not fail in case of eovercrowded.

2024-10-08 02:41 UTC, superhail commented
@chenBright please help check

2024-10-12 04:46 UTC, superhail commented
@chenBright http2 needed as well?

2024-10-12 05:44 UTC, wwbmmm commented on src/brpc/server.cpp
> +static bool g_default_ignore_eovercrowded(false);
where is this used?

2024-10-14 02:48 UTC, superhail commented on src/brpc/server.cpp
> +static bool g_default_ignore_eovercrowded(false);
i will delete it

2024-10-14 03:04 UTC, superhail commented
@wwbmmm @chenBright all done

2024-10-14 06:00 UTC, wwbmmm commented
LGTM

2024-10-14 06:05 UTC, chenBright approved these changes
LGTM

2024-10-14 06:06 UTC, merged